image: mwienk/docker-lftp:latest
stages:
  - deploy
deploy:
    stage: deploy
    script:
    - lftp -c 'open -u $USERNAME,$PASSWORD sftp://$HOSTNAME -p $PORT;set sftp:auto-confirm yes;set ssl:verify-certificate no;set net:max-retries 5;set net:timeout 1;mirror -Rev ./ ./ --parallel=10 --exclude-glob .git* --exclude .git/ --exclude exampleFolder/;quit'
    only:
    - master
